apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: shorturl-redis
  name: shorturl-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorturl-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shorturl-redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: IfNotPresent
        name: shorturl-redis
        ports:
        - containerPort: 6379
          name: redis-expose
---
kind: Service
apiVersion: v1
metadata:
  name: shorturl-redis-expose
spec:
  selector:
    app: shorturl-redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30079
  type: NodePort
